python_library(
  name = 'collectors',
  sources = rglobs('*.py'),
  dependencies = [
    '3rdparty/python:configobj',
    '3rdparty/python:psutil',
    '3rdparty/python:PyYAML',
    '3rdparty/python:subprocess32'
  ],
)
